### ISSUE TITLE
After race GPS track - enhancement suggestion

### ISSUE THREAD

**Issue by Alecto55555** [Laverlin/Yet-Another-Sailing-App#36]
Hi, I have been enjoying your app for a number of years.  I have a suggested enhancement.  I like to analyse my track after the race.  Instead of a red line, would it be possible to provide a coloured speed indication in the line.  So you can see how fast you were going at any particular point on the race course.  A max and min speed marker would be icing on that cake.  Kind regards, Charles.

**Comment by yet-an-other** [comment]
The app is actually doing nothing with the track, it just provides the raw data to garmin. So, unfortunately, any enhancements need to be done on the garmin side.

**Comment by Alecto55555** [comment]
Many thanks for your reply.  Is this something I should take up with Garmin?  The reason I ask is that if I am using ‘their’ apps for running and walking, the track displayed is colour coded to reflect the speed.  By inference, are you suggesting that Garmin need to flip a switch to enable colour coded tracks on your app?

Kind regards,

Charles.

From: yet-an-other ***@***.***>
Reply to: Laverlin/Yet-Another-Sailing-App ***@***.***>
Date: Thursday, 14 March 2024 at 23:26
To: Laverlin/Yet-Another-Sailing-App ***@***.***>
Cc: Alecto55555 ***@***.***>, Author ***@***.***>
Subject: Re: [Laverlin/Yet-Another-Sailing-App] After race GPS track - enhancement suggestion (Issue #36)


The app is actually doing nothing with the track, it just provides the raw data to garmin. So, unfortunately, any enhancements need to be done on the garmin side.
