### ISSUE TITLE
Add way points

### ISSUE THREAD

**Issue by Laverlin** [Laverlin/Yet-Another-Sailing-App#5]
Setup way points as course & distance, or as lon/lat coordinates and show heading and distance.

**Comment by dududu13** [comment]
Hi Laverlin
I really apprreciate your app
I've started to developp mine, but I realized that Fenix 3 doesn't support waypoint management, and it was a great deception
I'm a new and don't know anaything in Monkey C.
My waypoints are in a XML file, and i Wonder if we could read a xml file with monkey C ?

**Comment by Laverlin** [comment]
Hi,
Well, Monkey C does not support XML processing, as far as I know, but real problem is that whole watch environment does not support read/write in separate file. You can only work with default setting storage..

**Comment by dududu13** [comment]
Hi,

I’ve used your app, to make mine, with waypoints in the XML property file

Cause of the low memory, I have supressed some things (the laps)

The app is in JP

There are sometime a bug, I think sometime, out of memory, or when the speed is = 0. I have to debug a little

The max of waypoints is about 60, they are in the resources/property.xml file

I think it would be possible to develop an interface to suppress, modify or add the waypoints, but it is a little too hard for me. In the app, are the waypoints for me.

I’m a newbie in java, I don’t know anything (and I don’t speak English), and I think there are still many things to do to economise the memory 

I would like to publish it in Garmin, with another name, if you are OK ?
[YA Sailing.zip](https://github.com/Laverlin/Yet-Another-Sailing-App/files/706758/YA.Sailing.zip)

**Comment by Laverlin** [comment]
Yeah, sure, feel free to publish it.

**Comment by Laverlin** [comment]
Route mode (waypoints) has been implemented
